object Clientes: TClientes
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'frm_cadastro'
  ClientHeight = 657
  ClientWidth = 1104
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
end
